//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HQModel", "FK_PageAya_Aya", "Aya", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DNE.WebMedia.Client.Aya), "PageAya", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DNE.WebMedia.Client.PageAya), true)]

#endregion

namespace DNE.WebMedia.Client
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HQEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HQEntities object using the connection string found in the 'HQEntities' section of the application configuration file.
        /// </summary>
        public HQEntities() : base("name=HQEntities", "HQEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HQEntities object.
        /// </summary>
        public HQEntities(string connectionString) : base(connectionString, "HQEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HQEntities object.
        /// </summary>
        public HQEntities(EntityConnection connection) : base(connection, "HQEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Medium> Media
        {
            get
            {
                if ((_Media == null))
                {
                    _Media = base.CreateObjectSet<Medium>("Media");
                }
                return _Media;
            }
        }
        private ObjectSet<Medium> _Media;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MediaInfo> MediaInfoes
        {
            get
            {
                if ((_MediaInfoes == null))
                {
                    _MediaInfoes = base.CreateObjectSet<MediaInfo>("MediaInfoes");
                }
                return _MediaInfoes;
            }
        }
        private ObjectSet<MediaInfo> _MediaInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aya> Ayas
        {
            get
            {
                if ((_Ayas == null))
                {
                    _Ayas = base.CreateObjectSet<Aya>("Ayas");
                }
                return _Ayas;
            }
        }
        private ObjectSet<Aya> _Ayas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PageAya> PageAyas
        {
            get
            {
                if ((_PageAyas == null))
                {
                    _PageAyas = base.CreateObjectSet<PageAya>("PageAyas");
                }
                return _PageAyas;
            }
        }
        private ObjectSet<PageAya> _PageAyas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Media EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedia(Medium medium)
        {
            base.AddObject("Media", medium);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediaInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediaInfoes(MediaInfo mediaInfo)
        {
            base.AddObject("MediaInfoes", mediaInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ayas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAyas(Aya aya)
        {
            base.AddObject("Ayas", aya);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PageAyas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPageAyas(PageAya pageAya)
        {
            base.AddObject("PageAyas", pageAya);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="soorehId">No Metadata Documentation available.</param>
        /// <param name="sooreh">No Metadata Documentation available.</param>
        /// <param name="ayehId">No Metadata Documentation available.</param>
        /// <param name="ayeh">No Metadata Documentation available.</param>
        public int InsertAyeh(Nullable<global::System.Int32> soorehId, global::System.String sooreh, Nullable<global::System.Int32> ayehId, global::System.String ayeh)
        {
            ObjectParameter soorehIdParameter;
            if (soorehId.HasValue)
            {
                soorehIdParameter = new ObjectParameter("SoorehId", soorehId);
            }
            else
            {
                soorehIdParameter = new ObjectParameter("SoorehId", typeof(global::System.Int32));
            }
    
            ObjectParameter soorehParameter;
            if (sooreh != null)
            {
                soorehParameter = new ObjectParameter("Sooreh", sooreh);
            }
            else
            {
                soorehParameter = new ObjectParameter("Sooreh", typeof(global::System.String));
            }
    
            ObjectParameter ayehIdParameter;
            if (ayehId.HasValue)
            {
                ayehIdParameter = new ObjectParameter("ayehId", ayehId);
            }
            else
            {
                ayehIdParameter = new ObjectParameter("ayehId", typeof(global::System.Int32));
            }
    
            ObjectParameter ayehParameter;
            if (ayeh != null)
            {
                ayehParameter = new ObjectParameter("Ayeh", ayeh);
            }
            else
            {
                ayehParameter = new ObjectParameter("Ayeh", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("InsertAyeh", soorehIdParameter, soorehParameter, ayehIdParameter, ayehParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="soorehId">No Metadata Documentation available.</param>
        /// <param name="sooreh">No Metadata Documentation available.</param>
        /// <param name="ayehId">No Metadata Documentation available.</param>
        /// <param name="ayeh">No Metadata Documentation available.</param>
        public int UpdateAyeh(Nullable<global::System.Int32> soorehId, global::System.String sooreh, Nullable<global::System.Int32> ayehId, global::System.String ayeh)
        {
            ObjectParameter soorehIdParameter;
            if (soorehId.HasValue)
            {
                soorehIdParameter = new ObjectParameter("SoorehId", soorehId);
            }
            else
            {
                soorehIdParameter = new ObjectParameter("SoorehId", typeof(global::System.Int32));
            }
    
            ObjectParameter soorehParameter;
            if (sooreh != null)
            {
                soorehParameter = new ObjectParameter("Sooreh", sooreh);
            }
            else
            {
                soorehParameter = new ObjectParameter("Sooreh", typeof(global::System.String));
            }
    
            ObjectParameter ayehIdParameter;
            if (ayehId.HasValue)
            {
                ayehIdParameter = new ObjectParameter("ayehId", ayehId);
            }
            else
            {
                ayehIdParameter = new ObjectParameter("ayehId", typeof(global::System.Int32));
            }
    
            ObjectParameter ayehParameter;
            if (ayeh != null)
            {
                ayehParameter = new ObjectParameter("Ayeh", ayeh);
            }
            else
            {
                ayehParameter = new ObjectParameter("Ayeh", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("UpdateAyeh", soorehIdParameter, soorehParameter, ayehIdParameter, ayehParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        /// <param name="persian">No Metadata Documentation available.</param>
        public int UpdatePersianAya(Nullable<global::System.Int32> id, global::System.String persian)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("id", id);
            }
            else
            {
                idParameter = new ObjectParameter("id", typeof(global::System.Int32));
            }
    
            ObjectParameter persianParameter;
            if (persian != null)
            {
                persianParameter = new ObjectParameter("persian", persian);
            }
            else
            {
                persianParameter = new ObjectParameter("persian", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("UpdatePersianAya", idParameter, persianParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="ayaId">No Metadata Documentation available.</param>
        /// <param name="langId">No Metadata Documentation available.</param>
        /// <param name="lang">No Metadata Documentation available.</param>
        /// <param name="translatedBy">No Metadata Documentation available.</param>
        /// <param name="text">No Metadata Documentation available.</param>
        public int InsertTranslate(Nullable<global::System.Int32> ayaId, global::System.String langId, global::System.String lang, global::System.String translatedBy, global::System.String text)
        {
            ObjectParameter ayaIdParameter;
            if (ayaId.HasValue)
            {
                ayaIdParameter = new ObjectParameter("AyaId", ayaId);
            }
            else
            {
                ayaIdParameter = new ObjectParameter("AyaId", typeof(global::System.Int32));
            }
    
            ObjectParameter langIdParameter;
            if (langId != null)
            {
                langIdParameter = new ObjectParameter("LangId", langId);
            }
            else
            {
                langIdParameter = new ObjectParameter("LangId", typeof(global::System.String));
            }
    
            ObjectParameter langParameter;
            if (lang != null)
            {
                langParameter = new ObjectParameter("Lang", lang);
            }
            else
            {
                langParameter = new ObjectParameter("Lang", typeof(global::System.String));
            }
    
            ObjectParameter translatedByParameter;
            if (translatedBy != null)
            {
                translatedByParameter = new ObjectParameter("TranslatedBy", translatedBy);
            }
            else
            {
                translatedByParameter = new ObjectParameter("TranslatedBy", typeof(global::System.String));
            }
    
            ObjectParameter textParameter;
            if (text != null)
            {
                textParameter = new ObjectParameter("Text", text);
            }
            else
            {
                textParameter = new ObjectParameter("Text", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("InsertTranslate", ayaIdParameter, langIdParameter, langParameter, translatedByParameter, textParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        /// <param name="ayeh">No Metadata Documentation available.</param>
        public int UpdateAyehText(Nullable<global::System.Int32> id, global::System.String ayeh)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("Id", id);
            }
            else
            {
                idParameter = new ObjectParameter("Id", typeof(global::System.Int32));
            }
    
            ObjectParameter ayehParameter;
            if (ayeh != null)
            {
                ayehParameter = new ObjectParameter("Ayeh", ayeh);
            }
            else
            {
                ayehParameter = new ObjectParameter("Ayeh", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("UpdateAyehText", idParameter, ayehParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="pageId">No Metadata Documentation available.</param>
        /// <param name="suraNo">No Metadata Documentation available.</param>
        /// <param name="ayaNo">No Metadata Documentation available.</param>
        public int InsertPageAya(Nullable<global::System.Int32> pageId, Nullable<global::System.Int32> suraNo, Nullable<global::System.Int32> ayaNo)
        {
            ObjectParameter pageIdParameter;
            if (pageId.HasValue)
            {
                pageIdParameter = new ObjectParameter("PageId", pageId);
            }
            else
            {
                pageIdParameter = new ObjectParameter("PageId", typeof(global::System.Int32));
            }
    
            ObjectParameter suraNoParameter;
            if (suraNo.HasValue)
            {
                suraNoParameter = new ObjectParameter("SuraNo", suraNo);
            }
            else
            {
                suraNoParameter = new ObjectParameter("SuraNo", typeof(global::System.Int32));
            }
    
            ObjectParameter ayaNoParameter;
            if (ayaNo.HasValue)
            {
                ayaNoParameter = new ObjectParameter("AyaNo", ayaNo);
            }
            else
            {
                ayaNoParameter = new ObjectParameter("AyaNo", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("InsertPageAya", pageIdParameter, suraNoParameter, ayaNoParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HQModel", Name="Aya")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aya : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aya object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="suraId">Initial value of the SuraId property.</param>
        /// <param name="ayaId">Initial value of the AyaId property.</param>
        /// <param name="sura">Initial value of the sura property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="textFull">Initial value of the TextFull property.</param>
        public static Aya CreateAya(global::System.Int32 id, global::System.Int32 suraId, global::System.Int32 ayaId, global::System.String sura, global::System.String text, global::System.String textFull)
        {
            Aya aya = new Aya();
            aya.Id = id;
            aya.SuraId = suraId;
            aya.AyaId = ayaId;
            aya.sura = sura;
            aya.Text = text;
            aya.TextFull = textFull;
            return aya;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SuraId
        {
            get
            {
                return _SuraId;
            }
            set
            {
                OnSuraIdChanging(value);
                ReportPropertyChanging("SuraId");
                _SuraId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuraId");
                OnSuraIdChanged();
            }
        }
        private global::System.Int32 _SuraId;
        partial void OnSuraIdChanging(global::System.Int32 value);
        partial void OnSuraIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AyaId
        {
            get
            {
                return _AyaId;
            }
            set
            {
                OnAyaIdChanging(value);
                ReportPropertyChanging("AyaId");
                _AyaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AyaId");
                OnAyaIdChanged();
            }
        }
        private global::System.Int32 _AyaId;
        partial void OnAyaIdChanging(global::System.Int32 value);
        partial void OnAyaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sura
        {
            get
            {
                return _sura;
            }
            set
            {
                OnsuraChanging(value);
                ReportPropertyChanging("sura");
                _sura = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sura");
                OnsuraChanged();
            }
        }
        private global::System.String _sura;
        partial void OnsuraChanging(global::System.String value);
        partial void OnsuraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TextFull
        {
            get
            {
                return _TextFull;
            }
            set
            {
                OnTextFullChanging(value);
                ReportPropertyChanging("TextFull");
                _TextFull = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TextFull");
                OnTextFullChanged();
            }
        }
        private global::System.String _TextFull;
        partial void OnTextFullChanging(global::System.String value);
        partial void OnTextFullChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HQModel", "FK_PageAya_Aya", "PageAya")]
        public PageAya PageAya
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageAya>("HQModel.FK_PageAya_Aya", "PageAya").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageAya>("HQModel.FK_PageAya_Aya", "PageAya").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PageAya> PageAyaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PageAya>("HQModel.FK_PageAya_Aya", "PageAya");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PageAya>("HQModel.FK_PageAya_Aya", "PageAya", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HQModel", Name="MediaInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediaInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediaInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="media_Id">Initial value of the Media_Id property.</param>
        /// <param name="fileType">Initial value of the FileType property.</param>
        /// <param name="duration">Initial value of the Duration property.</param>
        /// <param name="lenght">Initial value of the Lenght property.</param>
        public static MediaInfo CreateMediaInfo(global::System.Int64 id, global::System.Int64 media_Id, global::System.String fileType, global::System.TimeSpan duration, global::System.Int64 lenght)
        {
            MediaInfo mediaInfo = new MediaInfo();
            mediaInfo.Id = id;
            mediaInfo.Media_Id = media_Id;
            mediaInfo.FileType = fileType;
            mediaInfo.Duration = duration;
            mediaInfo.Lenght = lenght;
            return mediaInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Media_Id
        {
            get
            {
                return _Media_Id;
            }
            set
            {
                OnMedia_IdChanging(value);
                ReportPropertyChanging("Media_Id");
                _Media_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Media_Id");
                OnMedia_IdChanged();
            }
        }
        private global::System.Int64 _Media_Id;
        partial void OnMedia_IdChanging(global::System.Int64 value);
        partial void OnMedia_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileType
        {
            get
            {
                return _FileType;
            }
            set
            {
                OnFileTypeChanging(value);
                ReportPropertyChanging("FileType");
                _FileType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileType");
                OnFileTypeChanged();
            }
        }
        private global::System.String _FileType;
        partial void OnFileTypeChanging(global::System.String value);
        partial void OnFileTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.TimeSpan _Duration;
        partial void OnDurationChanging(global::System.TimeSpan value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Lenght
        {
            get
            {
                return _Lenght;
            }
            set
            {
                OnLenghtChanging(value);
                ReportPropertyChanging("Lenght");
                _Lenght = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lenght");
                OnLenghtChanged();
            }
        }
        private global::System.Int64 _Lenght;
        partial void OnLenghtChanging(global::System.Int64 value);
        partial void OnLenghtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HQModel", Name="Medium")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medium : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Medium object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="story">Initial value of the Story property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="addDate">Initial value of the AddDate property.</param>
        /// <param name="editDate">Initial value of the EditDate property.</param>
        public static Medium CreateMedium(global::System.Int64 id, global::System.String title, global::System.String story, global::System.Byte[] body, global::System.String userName, global::System.DateTime addDate, global::System.DateTime editDate)
        {
            Medium medium = new Medium();
            medium.Id = id;
            medium.Title = title;
            medium.Story = story;
            medium.Body = body;
            medium.UserName = userName;
            medium.AddDate = addDate;
            medium.EditDate = editDate;
            return medium;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Story
        {
            get
            {
                return _Story;
            }
            set
            {
                OnStoryChanging(value);
                ReportPropertyChanging("Story");
                _Story = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Story");
                OnStoryChanged();
            }
        }
        private global::System.String _Story;
        partial void OnStoryChanging(global::System.String value);
        partial void OnStoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Body
        {
            get
            {
                return StructuralObject.GetValidValue(_Body);
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.Byte[] _Body;
        partial void OnBodyChanging(global::System.Byte[] value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddDate
        {
            get
            {
                return _AddDate;
            }
            set
            {
                OnAddDateChanging(value);
                ReportPropertyChanging("AddDate");
                _AddDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddDate");
                OnAddDateChanged();
            }
        }
        private global::System.DateTime _AddDate;
        partial void OnAddDateChanging(global::System.DateTime value);
        partial void OnAddDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EditDate
        {
            get
            {
                return _EditDate;
            }
            set
            {
                OnEditDateChanging(value);
                ReportPropertyChanging("EditDate");
                _EditDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditDate");
                OnEditDateChanged();
            }
        }
        private global::System.DateTime _EditDate;
        partial void OnEditDateChanging(global::System.DateTime value);
        partial void OnEditDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HQModel", Name="PageAya")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PageAya : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PageAya object.
        /// </summary>
        /// <param name="ayaId">Initial value of the AyaId property.</param>
        /// <param name="pageId">Initial value of the PageId property.</param>
        /// <param name="suraNo">Initial value of the SuraNo property.</param>
        /// <param name="ayaNo">Initial value of the AyaNo property.</param>
        public static PageAya CreatePageAya(global::System.Int32 ayaId, global::System.Int32 pageId, global::System.Int32 suraNo, global::System.Int32 ayaNo)
        {
            PageAya pageAya = new PageAya();
            pageAya.AyaId = ayaId;
            pageAya.PageId = pageId;
            pageAya.SuraNo = suraNo;
            pageAya.AyaNo = ayaNo;
            return pageAya;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AyaId
        {
            get
            {
                return _AyaId;
            }
            set
            {
                if (_AyaId != value)
                {
                    OnAyaIdChanging(value);
                    ReportPropertyChanging("AyaId");
                    _AyaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AyaId");
                    OnAyaIdChanged();
                }
            }
        }
        private global::System.Int32 _AyaId;
        partial void OnAyaIdChanging(global::System.Int32 value);
        partial void OnAyaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageId
        {
            get
            {
                return _PageId;
            }
            set
            {
                OnPageIdChanging(value);
                ReportPropertyChanging("PageId");
                _PageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageId");
                OnPageIdChanged();
            }
        }
        private global::System.Int32 _PageId;
        partial void OnPageIdChanging(global::System.Int32 value);
        partial void OnPageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SuraNo
        {
            get
            {
                return _SuraNo;
            }
            set
            {
                OnSuraNoChanging(value);
                ReportPropertyChanging("SuraNo");
                _SuraNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuraNo");
                OnSuraNoChanged();
            }
        }
        private global::System.Int32 _SuraNo;
        partial void OnSuraNoChanging(global::System.Int32 value);
        partial void OnSuraNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AyaNo
        {
            get
            {
                return _AyaNo;
            }
            set
            {
                OnAyaNoChanging(value);
                ReportPropertyChanging("AyaNo");
                _AyaNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AyaNo");
                OnAyaNoChanged();
            }
        }
        private global::System.Int32 _AyaNo;
        partial void OnAyaNoChanging(global::System.Int32 value);
        partial void OnAyaNoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HQModel", "FK_PageAya_Aya", "Aya")]
        public Aya Aya
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aya>("HQModel.FK_PageAya_Aya", "Aya").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aya>("HQModel.FK_PageAya_Aya", "Aya").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Aya> AyaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aya>("HQModel.FK_PageAya_Aya", "Aya");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Aya>("HQModel.FK_PageAya_Aya", "Aya", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HQModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="screenName">Initial value of the ScreenName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="openId">Initial value of the OpenId property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String userName, global::System.String screenName, global::System.String email, global::System.String password, global::System.String openId)
        {
            User user = new User();
            user.Id = id;
            user.UserName = userName;
            user.ScreenName = screenName;
            user.Email = email;
            user.Password = password;
            user.OpenId = openId;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScreenName
        {
            get
            {
                return _ScreenName;
            }
            set
            {
                OnScreenNameChanging(value);
                ReportPropertyChanging("ScreenName");
                _ScreenName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScreenName");
                OnScreenNameChanged();
            }
        }
        private global::System.String _ScreenName;
        partial void OnScreenNameChanging(global::System.String value);
        partial void OnScreenNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OpenId
        {
            get
            {
                return _OpenId;
            }
            set
            {
                OnOpenIdChanging(value);
                ReportPropertyChanging("OpenId");
                _OpenId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OpenId");
                OnOpenIdChanged();
            }
        }
        private global::System.String _OpenId;
        partial void OnOpenIdChanging(global::System.String value);
        partial void OnOpenIdChanged();

        #endregion
    
    }

    #endregion
    
}
