//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DNE.WebMedia.Model", "FK_Translate_Aya", "Aya", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DNE.WebMedia.Model.Aya), "Translate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DNE.WebMedia.Model.Translate), true)]

#endregion

namespace DNE.WebMedia.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HQEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HQEntities object using the connection string found in the 'HQEntities' section of the application configuration file.
        /// </summary>
        public HQEntities() : base("name=HQEntities", "HQEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HQEntities object.
        /// </summary>
        public HQEntities(string connectionString) : base(connectionString, "HQEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HQEntities object.
        /// </summary>
        public HQEntities(EntityConnection connection) : base(connection, "HQEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aya> Aya
        {
            get
            {
                if ((_Aya == null))
                {
                    _Aya = base.CreateObjectSet<Aya>("Aya");
                }
                return _Aya;
            }
        }
        private ObjectSet<Aya> _Aya;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Media> Media
        {
            get
            {
                if ((_Media == null))
                {
                    _Media = base.CreateObjectSet<Media>("Media");
                }
                return _Media;
            }
        }
        private ObjectSet<Media> _Media;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MediaInfo> MediaInfo
        {
            get
            {
                if ((_MediaInfo == null))
                {
                    _MediaInfo = base.CreateObjectSet<MediaInfo>("MediaInfo");
                }
                return _MediaInfo;
            }
        }
        private ObjectSet<MediaInfo> _MediaInfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        new public ObjectSet<Translate> Translate
        {
            get
            {
                if ((_Translate == null))
                {
                    _Translate = base.CreateObjectSet<Translate>("Translate");
                }
                return _Translate;
            }
        }
        private ObjectSet<Translate> _Translate;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Aya EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAya(Aya aya)
        {
            base.AddObject("Aya", aya);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Media EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedia(Media media)
        {
            base.AddObject("Media", media);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediaInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediaInfo(MediaInfo mediaInfo)
        {
            base.AddObject("MediaInfo", mediaInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Translate EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTranslate(Translate translate)
        {
            base.AddObject("Translate", translate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion
    }
    

    #endregion
    
    #region HQEntities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DNE.WebMedia.Model", Name="Aya")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aya : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aya object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="suraId">Initial value of the SuraId property.</param>
        /// <param name="ayaId">Initial value of the AyaId property.</param>
        /// <param name="sura">Initial value of the sura property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="textFull">Initial value of the TextFull property.</param>
        public static Aya CreateAya(global::System.Int32 id, global::System.Int32 suraId, global::System.Int32 ayaId, global::System.String sura, global::System.String text, global::System.String textFull)
        {
            Aya aya = new Aya();
            aya.Id = id;
            aya.SuraId = suraId;
            aya.AyaId = ayaId;
            aya.sura = sura;
            aya.Text = text;
            aya.TextFull = textFull;
            return aya;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SuraId
        {
            get
            {
                return _SuraId;
            }
            set
            {
                OnSuraIdChanging(value);
                ReportPropertyChanging("SuraId");
                _SuraId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuraId");
                OnSuraIdChanged();
            }
        }
        private global::System.Int32 _SuraId;
        partial void OnSuraIdChanging(global::System.Int32 value);
        partial void OnSuraIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AyaId
        {
            get
            {
                return _AyaId;
            }
            set
            {
                OnAyaIdChanging(value);
                ReportPropertyChanging("AyaId");
                _AyaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AyaId");
                OnAyaIdChanged();
            }
        }
        private global::System.Int32 _AyaId;
        partial void OnAyaIdChanging(global::System.Int32 value);
        partial void OnAyaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sura
        {
            get
            {
                return _sura;
            }
            set
            {
                OnsuraChanging(value);
                ReportPropertyChanging("sura");
                _sura = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sura");
                OnsuraChanged();
            }
        }
        private global::System.String _sura;
        partial void OnsuraChanging(global::System.String value);
        partial void OnsuraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TextFull
        {
            get
            {
                return _TextFull;
            }
            set
            {
                OnTextFullChanging(value);
                ReportPropertyChanging("TextFull");
                _TextFull = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TextFull");
                OnTextFullChanged();
            }
        }
        private global::System.String _TextFull;
        partial void OnTextFullChanging(global::System.String value);
        partial void OnTextFullChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DNE.WebMedia.Model", "FK_Translate_Aya", "Translate")]
        public EntityCollection<Translate> Translate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Translate>("DNE.WebMedia.Model.FK_Translate_Aya", "Translate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Translate>("DNE.WebMedia.Model.FK_Translate_Aya", "Translate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DNE.WebMedia.Model", Name="Media")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Media : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Media object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="story">Initial value of the Story property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="addDate">Initial value of the AddDate property.</param>
        /// <param name="editDate">Initial value of the EditDate property.</param>
        public static Media CreateMedia(global::System.Int64 id, global::System.String title, global::System.String story, global::System.Byte[] body, global::System.String userName, global::System.DateTime addDate, global::System.DateTime editDate)
        {
            Media media = new Media();
            media.Id = id;
            media.Title = title;
            media.Story = story;
            media.Body = body;
            media.UserName = userName;
            media.AddDate = addDate;
            media.EditDate = editDate;
            return media;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Story
        {
            get
            {
                return _Story;
            }
            set
            {
                OnStoryChanging(value);
                ReportPropertyChanging("Story");
                _Story = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Story");
                OnStoryChanged();
            }
        }
        private global::System.String _Story;
        partial void OnStoryChanging(global::System.String value);
        partial void OnStoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Body
        {
            get
            {
                return StructuralObject.GetValidValue(_Body);
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.Byte[] _Body;
        partial void OnBodyChanging(global::System.Byte[] value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddDate
        {
            get
            {
                return _AddDate;
            }
            set
            {
                OnAddDateChanging(value);
                ReportPropertyChanging("AddDate");
                _AddDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddDate");
                OnAddDateChanged();
            }
        }
        private global::System.DateTime _AddDate;
        partial void OnAddDateChanging(global::System.DateTime value);
        partial void OnAddDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EditDate
        {
            get
            {
                return _EditDate;
            }
            set
            {
                OnEditDateChanging(value);
                ReportPropertyChanging("EditDate");
                _EditDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditDate");
                OnEditDateChanged();
            }
        }
        private global::System.DateTime _EditDate;
        partial void OnEditDateChanging(global::System.DateTime value);
        partial void OnEditDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DNE.WebMedia.Model", Name="MediaInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediaInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediaInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="media_Id">Initial value of the Media_Id property.</param>
        /// <param name="fileType">Initial value of the FileType property.</param>
        /// <param name="duration">Initial value of the Duration property.</param>
        /// <param name="lenght">Initial value of the Lenght property.</param>
        public static MediaInfo CreateMediaInfo(global::System.Int64 id, global::System.Int64 media_Id, global::System.String fileType, global::System.TimeSpan duration, global::System.Int64 lenght)
        {
            MediaInfo mediaInfo = new MediaInfo();
            mediaInfo.Id = id;
            mediaInfo.Media_Id = media_Id;
            mediaInfo.FileType = fileType;
            mediaInfo.Duration = duration;
            mediaInfo.Lenght = lenght;
            return mediaInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Media_Id
        {
            get
            {
                return _Media_Id;
            }
            set
            {
                OnMedia_IdChanging(value);
                ReportPropertyChanging("Media_Id");
                _Media_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Media_Id");
                OnMedia_IdChanged();
            }
        }
        private global::System.Int64 _Media_Id;
        partial void OnMedia_IdChanging(global::System.Int64 value);
        partial void OnMedia_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileType
        {
            get
            {
                return _FileType;
            }
            set
            {
                OnFileTypeChanging(value);
                ReportPropertyChanging("FileType");
                _FileType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileType");
                OnFileTypeChanged();
            }
        }
        private global::System.String _FileType;
        partial void OnFileTypeChanging(global::System.String value);
        partial void OnFileTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.TimeSpan _Duration;
        partial void OnDurationChanging(global::System.TimeSpan value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Lenght
        {
            get
            {
                return _Lenght;
            }
            set
            {
                OnLenghtChanging(value);
                ReportPropertyChanging("Lenght");
                _Lenght = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lenght");
                OnLenghtChanged();
            }
        }
        private global::System.Int64 _Lenght;
        partial void OnLenghtChanging(global::System.Int64 value);
        partial void OnLenghtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DNE.WebMedia.Model", Name="Translate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Translate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Translate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ayaId">Initial value of the AyaId property.</param>
        /// <param name="langId">Initial value of the LangId property.</param>
        /// <param name="lang">Initial value of the Lang property.</param>
        /// <param name="translatedBy">Initial value of the TranslatedBy property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="direction">Initial value of the Direction property.</param>
        public static Translate CreateTranslate(global::System.Int64 id, global::System.Int32 ayaId, global::System.String langId, global::System.String lang, global::System.String translatedBy, global::System.String text, global::System.String direction)
        {
            Translate translate = new Translate();
            translate.Id = id;
            translate.AyaId = ayaId;
            translate.LangId = langId;
            translate.Lang = lang;
            translate.TranslatedBy = translatedBy;
            translate.Text = text;
            translate.Direction = direction;
            return translate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AyaId
        {
            get
            {
                return _AyaId;
            }
            set
            {
                OnAyaIdChanging(value);
                ReportPropertyChanging("AyaId");
                _AyaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AyaId");
                OnAyaIdChanged();
            }
        }
        private global::System.Int32 _AyaId;
        partial void OnAyaIdChanging(global::System.Int32 value);
        partial void OnAyaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LangId
        {
            get
            {
                return _LangId;
            }
            set
            {
                OnLangIdChanging(value);
                ReportPropertyChanging("LangId");
                _LangId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LangId");
                OnLangIdChanged();
            }
        }
        private global::System.String _LangId;
        partial void OnLangIdChanging(global::System.String value);
        partial void OnLangIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lang
        {
            get
            {
                return _Lang;
            }
            set
            {
                OnLangChanging(value);
                ReportPropertyChanging("Lang");
                _Lang = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lang");
                OnLangChanged();
            }
        }
        private global::System.String _Lang;
        partial void OnLangChanging(global::System.String value);
        partial void OnLangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TranslatedBy
        {
            get
            {
                return _TranslatedBy;
            }
            set
            {
                OnTranslatedByChanging(value);
                ReportPropertyChanging("TranslatedBy");
                _TranslatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TranslatedBy");
                OnTranslatedByChanged();
            }
        }
        private global::System.String _TranslatedBy;
        partial void OnTranslatedByChanging(global::System.String value);
        partial void OnTranslatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direction
        {
            get
            {
                return _Direction;
            }
            set
            {
                OnDirectionChanging(value);
                ReportPropertyChanging("Direction");
                _Direction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direction");
                OnDirectionChanged();
            }
        }
        private global::System.String _Direction;
        partial void OnDirectionChanging(global::System.String value);
        partial void OnDirectionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DNE.WebMedia.Model", "FK_Translate_Aya", "Aya")]
        public Aya Aya
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aya>("DNE.WebMedia.Model.FK_Translate_Aya", "Aya").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aya>("DNE.WebMedia.Model.FK_Translate_Aya", "Aya").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Aya> AyaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aya>("DNE.WebMedia.Model.FK_Translate_Aya", "Aya");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Aya>("DNE.WebMedia.Model.FK_Translate_Aya", "Aya", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DNE.WebMedia.Model", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="screenName">Initial value of the ScreenName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String userName, global::System.String screenName, global::System.String email, global::System.String password)
        {
            User user = new User();
            user.Id = id;
            user.UserName = userName;
            user.ScreenName = screenName;
            user.Email = email;
            user.Password = password;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScreenName
        {
            get
            {
                return _ScreenName;
            }
            set
            {
                OnScreenNameChanging(value);
                ReportPropertyChanging("ScreenName");
                _ScreenName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScreenName");
                OnScreenNameChanged();
            }
        }
        private global::System.String _ScreenName;
        partial void OnScreenNameChanging(global::System.String value);
        partial void OnScreenNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }

    #endregion
    
}
